### ISSUE TITLE
Problems with Android that works with iOS

### ISSUE THREAD

**Issue by Arnoho** [Yermo/nativescript-mapbox#162]
I have three problems that are working with iOS but not with Android.  I am using newest version of nativescript-mapbox (3.1.0) with Angular. Map is declared in main.ts and used in html:

`registerElement("Map", () => require("nativescript-mapbox").MapboxView);  `

```
<GridLayout height="30%" width="100%">
    <Map 
         mapStyle="streets"
         latitude="62"
         longitude="26"
         zoomLevel="4"
         hideLogo="true"
         showUserLocation="true"
         [accessToken]="mapboxAccessToken"
         (mapReady)="onMapReady($event)">
    </Map>
</GridLayout>
```

1.  After opening map first time with Android device it ask permission to use location (great!). After user press “accept” I need to call my special function (that focus map and show markers). How can I do that? I do that in onMapReady() function, but it is called before user have change to give permission to use location (which is needed to focus map etc..). Is there anyway to listen "permission is granted, call this function"?

2.  After updating nativescript-mapbox version 3.0.3 to 3.1.0 “showUserLocation” stopped working. I get this error “com.mapbox.mapboxsdk.location.LocationSource.getLocationEngine is not a function”. I get rid of this error when I change "showUserLocation" to false, but of course then It won't show user location. Problem happens only with Android, iOS is working just fine.
I guess it’s related to this old closed issue: https://github.com/EddyVerbruggen/nativescript-mapbox/issues/80 .

3. Third problem is related to angular child routes. I have view with map and list of items. I click one item and open it as child route and then I press back button. I get back to same view but map is missing. Problem happens when I use routerExtensions.back() function, instead of router.navigate(). Reason is probably that when I use back function, it cache the view and do not reload it again. For some reason it does not cache mapbox. Problem happens only with Android, iOS is working just fine. 
Probably related to https://github.com/EddyVerbruggen/nativescript-mapbox/issues/65 .

**Comment by EddyVerbruggen** [comment]
Hi,

1) You can now (version 3.1.1) add `locationPermissionGranted` to your XML-declared map. It works the same as the `mapReady` event.

2) Works again - they changed the native SDK once again, so I had to update some code as well.

3) No clue.

PS. Please create (3) separate issues next time.

**Comment by Arnoho** [comment]
Thank you! That was really quick!
Edit: Actually problem 2 is fixed now but problem 1 is still exists. I mean yes `locationPermissionGranted` get called but it is called just after `mapReady` and it does not wait until user have made decision to accept location.
